### PR TITLE
Fix #15

### LINKED ISSUE #15: CONFIGpac checksums are always wrong
Whenever I start a new connection with my P3DX-SH, I receive get the following warning:
`ArRobotPacketReceiver::receivePacket: Warning: bad packet, bad checksum (received packet type ID 0x20: Robot Config Packet)`

I dug deeper into AriaCoda's code and found out that there really is always a mismatch between CONFIGpac's reported checksum and calculated checksum, but it seems to me that according to the robot's manual (which I could only find here https://www.inf.ufrgs.br/~prestes/Courses/Robotics/manual_pioneer.pdf ) robot configuration packets seem to have no trailing checksum.

Would it make sense to ignore the packet checksum if it is a CONFIGpac? I could open a PR for that.

### PR DESCRIPTION
**Pull request by 314gomes**
Fix #15 by using variable type `unsigned char` to store the packet length, avoiding casting errrors resulting in negative values.

### CODE REVIEW

File: src/ArRobotPacket.cpp [hunk 1]
```diff
@@ -119,7 +119,7 @@ AREXPORT int16_t ArRobotPacket::calcCheckSum()
 {
   int16_t c = 0;
   int i = 3;
-  int n = (int) myBuf[2] - 2;
+  unsigned char n = myBuf[2] - 2;
```
Comment (reedhedges) [inline src/ArRobotPacket.cpp:122]: Underflow/wrap around of this value (i.e. if the byte in `myBuf[2]` is less than 2) is an expected behavior for the checksum algorithm, so we want to specifically allow this by using unsigned char type.

**Review by reedhedges — APPROVED** [review]
Thank you for your investigation and for fixing this bug!

**Comment by reedhedges** [comment]
I suppose we could also remove the check if n > 0 on line 129?  Maybe I'll put some comments in also re expected underflow/wraparound of `n` on line 122 and line 126.

File: src/ArRobotPacket.cpp (hunk 1 above)
Comment (reedhedges) [reply src/ArRobotPacket.cpp:122]: Actually myBuf[2] should be packet length, so we should probably just fail the checksum validation or throw some other error if the value is < 2.  I don't have too much time to look into this more, but anyone is welcome to. Since this fixes the main bug we'll merge this change as the fix for now.

**Comment by reedhedges** [comment]
Looks like there are a few opportunities to add new error checking here if we wanted to (see my comments above) but since this fixed the real bug and is the same algorithm and code that's has always been used in ARIA we'll merge this now, and if anyone feels that they want to make any additional improvements or think's its very important, we can open a new issue and discuss.

File: src/ArRobotPacket.cpp (hunk 1 above)
Comment (reedhedges) [reply src/ArRobotPacket.cpp:122]: My only other feedback is that an explicit cast here is nice, so I may add that if that's ok with you: `unsigned char n = (unsigned char) (myBuf[2] - 2);`

**Comment by 314gomes** [comment]
Yes, I do agree that the current code for the checksum is not optimal. I could look into that in the future and also supply data from more packets since I do have access to a physical robot, altough I would need greater help in writing the tests.

**Comment by reedhedges** [comment]
We can discuss tests in the "Discussion" section if you are interested https://github.com/reedhedges/AriaCoda/discussions
